CREATE DATABASE IF NOT EXISTS 'planets';

USE 'planets';

SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

CREATE TABLE IF NOT EXISTS 'planets' (
        id INT AUTO_INCREMENT NOT NULL, 
        name VARCHAR(255) NOT NULL, 
        day INT DEFAULT NULL, 
        month INT DEFAULT NULL, 
        PRIMARY KEY(id)
     DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
);